### PR TITLE
Parse IPv6 addresses in X-Forwarded-For header

### PR DESCRIPTION
**Pull request by kopytov**
Hello. I found that OLS 1.3 doesn't parse IPv6 addresses passed by X-Forwarded-For header (when UseClientIP is activated). This patch add ability to parse it. Please review.

### CODE REVIEW

**Comment by litespeedtech** [comment]
We have a slightly different patch for that. 

diff --git src/http/httpsession.cpp src/http/httpsession.cpp
index afdbba9..9020360 100644
--- src/http/httpsession.cpp
+++ src/http/httpsession.cpp
@@ -679,6 +679,9 @@ void HttpSession::processPending(int ret)
 int HttpSession::updateClientInfoFromProxyHeader(const char *pProxyHeader)
 {
     char achIP[128];
+    char achAddr[128];
+    struct sockaddr *pAddr;
+    void *pIP;
     int len = m_request.getHeaderLen(HttpHeader::H_X_FORWARDED_FOR);
     char *p = (char *)memchr(pProxyHeader, ',', len);
     if (p)
@@ -691,17 +694,24 @@ int HttpSession::updateClientInfoFromProxyHeader(const char *pProxyHeader)
 
     memmove(achIP, pProxyHeader, len);
     achIP[len] = 0;
-    struct sockaddr_in addr;
-    memset(&addr, 0, sizeof(sockaddr_in));
-    addr.sin_family = AF_INET;
-    addr.sin_addr.s_addr = inet_addr(achIP);
-    if (addr.sin_addr.s_addr == INADDR_BROADCAST)
+    pAddr = (struct sockaddr *)achAddr;
+    memset(pAddr, 0, sizeof(sockaddr_in6));
+
+    if (memchr(achIP, ':', len))
     {
-        //Failed to parse the address string to IPv4 address
-        return 0;
+        pAddr->sa_family = AF_INET6;
+        pIP = &((struct sockaddr_in6 *)pAddr)->sin6_addr;
     }
+    else
+    {
+        pAddr->sa_family = AF_INET;
+        pIP = &((struct sockaddr_in *)pAddr)->sin_addr;
+    }
+    if (inet_pton(pAddr->sa_family, achIP, pIP) != 1)
+        return 0;
+    
     ClientInfo *pInfo = HttpGlobals::getClientCache()
-                        ->getClientInfo((struct sockaddr *)&addr);
+                        ->getClientInfo(pAddr);
     if (pInfo)
     {
         if (pInfo->checkAccess())

**Comment by kopytov** [comment]
Great! Will you include it to next release of 1.3?

**Comment by litespeedtech** [comment]
Yes.

**Comment by kopytov** [comment]
Thanks.

**Pull request closed without merging**
